### PR TITLE
Placeholder for acceptance tests

### PR DESCRIPTION
**Pull request by Stephen-Gates**
Just getting started with tests.
Check PR review mechanics

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
@mattRedBox
- should the /tests directory should be renamed /features?
- should acknowledge-contributions.txt be renamed acknowledge-contributions.feature?

**Comment by Stephen-Gates** [comment]
@mattRedBox How's this?

Advice on blank lines between Given, Then When (or anything else) welcome.

**Comment by Stephen-Gates** [comment]
Not sure I'm writing these tests at the right level. Feedback welcome.

**Comment by Stephen-Gates** [comment]
set up Relish https://relishapp.com/odi-australia/data-curator/docs

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Think where you have features folder (ie: under test) is perfect.
Blank lines I only leave between scenarios and features as each of the Given/When/Thens provides some kinda syntax indicator (colour, indentation beneath) - more readable this way, for me anyway - too much whitespace makes it difficult to scan through I think.

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox. Will reduce white space tonight. Thoughts on edit data feature?

**Pull request merged**
