### PR TITLE
Sprint 1 features

### PR DESCRIPTION
**Pull request by Stephen-Gates**
Features for sprint 1.

Advice requested on how to do:

-  [menu.feature](https://github.com/ODIQueensland/data-curator/blob/83b8cc74bd41a41f26d2c14ecf7265e7211ffab8/test/features/backlog/menu.feature) for menu navigation
- [edit.feature](https://github.com/ODIQueensland/data-curator/blob/sprint-1-features/test/features/backlog/edit-data.feature) given very large number of menu and keyboard shortcuts 

What else is needed for this sprint?

- [ ] shortcuts
- [x] edit
- [ ] menu
- [x] Save all
- [x] Show Next / Previous Tab
- [x] Quit Data Curator?

@mattRedBox

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
@mattRedBox 
advice requested on keyboard shortcuts

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
For the menu - you don't need to specify OS-specific stuff - you can just say 'I use the shortcut menu item for Copy'

What would be useful though is to start to create a data table of the OS matrix for what shortcuts should be. 

[data-tables](https://cucumber.io/docs/reference#data-tables) is worth a look, but notice it is only useful for incoming data - I don't think we can actually use it like this given that the same test on the same machine won't be able to switch between OSs. Anyway doesn't really matter atm.

For other tests, [scenario outlines](https://cucumber.io/docs/reference#scenario-outline) 
can be useful to iterate through numerous given-when-thens with changing data and expectations. It gives you more flexibility than a simple data-table to update any part of the scenario with some kindof input/output.

Don't worry too much about how the table should look at this stage - as long as the shortcuts are recorded for each OS in table - that's all that matters for now

For the features themselves we can just say something once, like:
```
For each actual feature itself
Given I am an OS user
When I perform the Cut shortcut
Then the Cut action should be performed
```
Any code underwritten would pick up the OS and then match against the data-table.

**Comment by Stephen-Gates** [comment]
@mattRedBox shortcuts documented here but the Examples: fail when pushing to Relish

Any clues? 

https://github.com/ODIQueensland/data-curator/blob/sprint-1-features/test/features/backlog/menu-keyboard-shortcuts.feature

**Comment by Stephen-Gates** [comment]
Attempted to fix shortcuts - edits welcome @mattRedBox

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Are you able to add me as a collaborator to Relish project?

**Comment by Stephen-Gates** [comment]
@mattRedBox re-invited you to Relish

**Comment by mattRedBox** [comment]
Ok that worked, @Stephen-Gates 
What's the problem that you're seeing? Is it an error message? Or the features don't appear?
I just did a push from the features directory and got response:
sent:
Should I see more than this?

**Comment by mattRedBox** [comment]
aha.
Scratch that
@Stephen-Gates, I changed into the 'test' directory and the push seemed to work.
Could it be that you were in the wrong directory?
I guess 'features' has to be 1 directory down only

**Comment by mattRedBox** [comment]
oh, ok, saw the acknowledgement for 'fail' on the site. Think I've caught up now to what you're seeing

**Comment by Stephen-Gates** [comment]
Can you see https://relishapp.com/my/pushes ?
The output of the push is there. 

I'm failing on the Examples in  https://github.com/ODIQueensland/data-curator/blob/sprint-1-features/test/features/backlog/menu-keyboard-shortcuts.feature 

Perhaps I should rewrite using data tables?

**Comment by mattRedBox** [comment]
I'm guessing there's some sort of syntax problem.
Unfortunately there isn't much help available (I'll have a look at the gem and see if there's any extra tasks we can use).
I'm guessing either the formatting or the 'bar's that are in recent commits, it doesn't like. I would probably try to push less files at a time to see (maybe push the ones without first, and see if you can isolate what's causing the error).

**Comment by Stephen-Gates** [comment]
Something like...

Scenario: use menu keyboard shortcut
  Given I have opened Data Curator in a supported operating system
  And the following <operating system shortcuts> exist
    | command | windows shortcut | macos shortcut | linux shortcut |
    | help          | f1                          |                           | f1                    |

  When I use an <operating system shortcut>
  Then the <command> is initiated

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates,
It could be baulking, because you have 'scenario' instead of 'scenario_outline'.
When you use 'example', it must have 'scenario_outline', not 'scenario'

**Comment by Stephen-Gates** [comment]
@mattRedBox Success! Scenario Outline worked 

https://relishapp.com/odi-australia/data-curator/docs/backlog/initiate-feature-using-menu-keyboard-shortcut 

Not convinced that the Feature is written correctly.

Next step is to get .nav working

**Comment by mattRedBox** [comment]
Nice one.
I think what you have there is fine for now - I'm not 100% sure how the test will work across different OSes (might just have to have a trigger to pick this out separately if we get to code), but I think what you have there is the simplest/most readable way to present it  (and that's what matters).

**Pull request merged**
